
CREATE TABLE IF NOT EXISTS urls(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    created_at TIMESTAMP,
    CONSTRAINT pk_urls PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS url_checks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    status_code INT ,
    title VARCHAR(255),
    h1 VARCHAR(255),
    description TEXT,
    url_id BIGINT REFERENCES urls (id),
    created_at TIMESTAMP,
    CONSTRAINT pk_url_checks PRIMARY KEY (id)
);

