
CREATE TABLE IF NOT EXISTS url(
    url_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    created_at TIMESTAMP,
    CONSTRAINT primary_key_url PRIMARY KEY (url_id)
);

CREATE TABLE IF NOT EXISTS url_check (
    url_check_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    status_code INT ,
    title VARCHAR(255),
    h1 VARCHAR(255),
    description TEXT,
    url_id BIGINT REFERENCES url (url_id),
    created_at TIMESTAMP,
    CONSTRAINT primary_key_url_check PRIMARY KEY (url_check_id)
);

