DROP table if exists urls;

create table urls(
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
name varchar(255),
createdAt timestamp,
CONSTRAINT pk_urls PRIMARY KEY (id));

DROP table if exists url_checks;

CREATE TABLE url_checks (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
statusCode INT ,
title VARCHAR(255),
h1 VARCHAR(255),
description TEXT,
urlId BIGINT REFERENCES urls (id),
createdAt TIMESTAMP,
CONSTRAINT pk_url_checks PRIMARY KEY(id));
